name: HasSecurityDash
version: "0.1.0"
slug: hassecuritydash
description: "🛡️ Security control and monitoring for Home Assistant"
url: https://github.com/dkwolf1/HasSecurityDash
arch:
  - aarch64
  - amd64
startup: services
boot: auto
init: false
ingress: true
ingress_port: 8081
panel_icon: mdi:shield-search
panel_title: HasSecurityDash
host_network: true
hassio_api: true
privileged:
  - NET_ADMIN
  - NET_RAW
ports:
  8080/tcp: null
ports_description:
  8080/tcp: HasSecurityDash WebUI port (internal only)
environment:
  PUID: "8080"
  PGID: "8080"
  TZ: Europe/Amsterdam
map:
  - addon_config:rw
schema:
  TZ: str?
services: []
url: https://github.com/dkwolf1/HasSecurityDash
